spring:
  datasource:
    url: jdbc:postgresql://fillexc-db/fillexc?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: fillexcadmin
    password: freep4ss
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true